project:
  type: website
  output-dir: docs

website:
  title: "BIO66I"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: workshop2.qmd
        text: workshop2
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



