project:
  type: website
  output-dir: docs

website:
  title: "BIO66I"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: BIO00066I-workshop2.qmd
        text: "Workshop 2"
        
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



