---
title: "BIO00066I Workshop 3"
subtitle: "Cell Biology Data Analysis Workshop 3"

author: Daniel Jeffares
date: 2024-01-25
format:
    html:
        code-link: true
        toc: true
        number-sections: true
        toc-location: right
        toc-depth: 2
        
editor: source
---



# Learning objectives


::: callout-important
## Philosophy

Workshops are not a test. You may make a lot of mistakes - that is fine. It's OK to need help. the staff are here to help you, so don't be afraid to ask for help! :-)
:::

## Technical skills

Today we will work with plotting movement data from the Livecyte microscope. 

We will learn some new R plotting skills:

- `facet_wrap` a method to plot one variable split up over different treatments (or chromosomes, or days, or replicates)
- how to create a **correlation data frame** using the `correlate` function. This allows us to explore many correlations between different metrics. Typically, these metrics are stored in the *columns* of our data frames.


## Thinking like a data scientist

We encourage you to develop your data handling skills. By:
- keeping our script clear, simple, and well-annotated
- developing your own habits to keep your awareness on **what data the data contains**


::: callout-warning
## Know your data! 
To understand the biology captured in the data, you need to know what is in the data. At each step, be sure you know the rows, the columns and what they mean. Keep notes about this in your script.
:::

# Introduction

## The biology

Today, we will continue our quest to understand  **mesenchymal stromal cells (MSCs)**. Remember, the two clones we are studying were both obtained from *one person*, and they have been transformed with telomerase to make them immortal (so they don't age). Then, they have been cultured in a lab for years. 

In [workshop 2](https://djeffares.github.io/BIO66I/workshop2.html), we say that these two clones were different shapes. This time, we examine how they move. 

::: callout-tip
## Sometimes, it is a good question that makes a good scientist.
Why do these clones maintain different shapes after growing in the lab for so long? Why don't they revert to being the same?
:::


## The data
In this workshop we bla bla

## Research questions

- Do the two mesenchymal stromal cell clones move differently?
- What data set(s) are most relaible?
- What are the best parameters to distinguish them?


# Exercises

## Part 1

## Part 2

## Part 3

# Reflection

# After the workshop

## Consolodation exercises

Optional

## Planning for your report





